---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/amanbolat/dotfiles-2
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .gotconfig
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - aria2
  - git
  - go
  - gpg
  - tldr
  - hg
  - htop
  - httpie
#  - iperf
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - stormssh
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/drivers
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - docker
  - resilio-sync
  - skype
  - google-chrome
  - macvim
  - slack
  - vagrant
  - virtualbox
  - logitech-options

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password (6.7)" }
  - { id: 1091189122, name: "Bear (1.2.1)" }
  - { id: 540348655, name: "Monosnap" }
  - { id: 451108668, name: "QQ" }

mas_email: "amanbolat@me.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# Install iterm2 and themes
iterm_config_path: ~/dotfiles/iterm

#Viasite ansible configs
zsh_user: "{{ ansible_user_id }}"

# List of directories to create
dir_list:
  - ~/Code

# iterm2
iterm_prefs_folder: ~/.iterm

