---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  vars_prompt:
    - name: "mas_password"
      prompt: "Enter Mac AppStore password"
      private: yes

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    # Dotfiles should be installed last to change .rc files
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/directories.yml
      tags: ['dir']

    - include: tasks/zsh.yml
      tags: ['zsh']

    - include: tasks/iterm2.yml
      tags: ['iterm']

    - include: tasks/terminal.yml
      when: configure_terminal

    - include: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
