---
#- name: Install zsh
#  homebrew:
#    name: zsh
#    state: present

- name: Install Oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
  become: no

- name: Install zsh-autosuggestions
  git:
    repo: git://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: no

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Download powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
  become: no

- name: make zsh deafult shell
  user:
    name: "{{ zsh_user }}"
    shell: /usr/local/bin/zsh
  become: yes